"""empty message

Revision ID: 4f00f4cbff54
Revises: 096b33cbba51
Create Date: 2020-12-22 21:31:15.981526

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '4f00f4cbff54'
down_revision = '096b33cbba51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    op.add_column('article', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=now))
    op.add_column('article', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=now))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'updated_at')
    op.drop_column('article', 'created_at')
    # ### end Alembic commands ###
